### ISSUE TITLE
Infinite redirect bug

### ISSUE THREAD

**Issue by ghost** [Dev-CasperTheGhost/nextjs-faunadb-url-shortener#1]
I've found a bug in the URL shortener which allows to make an infinite redirect. 

Here's an example: https://ctgs.ga/index.php
After clicking on the link, it starts loading and then doesn't stop.

This can be done if an entered URL would match a shortened URL. I've attached a screenshot below.

![image](https://user-images.githubusercontent.com/73775612/114277683-deb03980-9a34-11eb-85f9-47da1566d1d3.png)

**Comment by casperiv0** [comment]
Thanks, will fix this now

**Comment by ghost** [comment]
A little update: Firefox recognises this bug and shows a "The page isn’t redirecting properly" error.

**Comment by casperiv0** [comment]
should be fixed in [this commit](https://github.com/Dev-CasperTheGhost/nextjs-faunadb-url-shortener/commit/4812684f6ac91d780fbf5e87d11c55d42f1f6f22)

**Comment by casperiv0** [comment]
atleast the slug part lol

**Comment by casperiv0** [comment]
Looks like it's all working now :D

![image](https://user-images.githubusercontent.com/53900565/114278347-b1ad5800-9a2f-11eb-91e4-24c0cc7f65ec.png)
